//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Gadget_Hub.localhost4 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CartServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CartService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCartItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCartTotalOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveFromCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckoutAndSaveOrdersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CartService() {
            this.Url = global::Gadget_Hub.Properties.Settings.Default.Gadget_Hub_localhost4_CartService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCartItemsCompletedEventHandler GetCartItemsCompleted;
        
        /// <remarks/>
        public event GetCartTotalCompletedEventHandler GetCartTotalCompleted;
        
        /// <remarks/>
        public event RemoveFromCartCompletedEventHandler RemoveFromCartCompleted;
        
        /// <remarks/>
        public event UpdateQuantityCompletedEventHandler UpdateQuantityCompleted;
        
        /// <remarks/>
        public event CheckoutAndSaveOrdersCompletedEventHandler CheckoutAndSaveOrdersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCartItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCartItems(int userId) {
            object[] results = this.Invoke("GetCartItems", new object[] {
                        userId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCartItemsAsync(int userId) {
            this.GetCartItemsAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetCartItemsAsync(int userId, object userState) {
            if ((this.GetCartItemsOperationCompleted == null)) {
                this.GetCartItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCartItemsOperationCompleted);
            }
            this.InvokeAsync("GetCartItems", new object[] {
                        userId}, this.GetCartItemsOperationCompleted, userState);
        }
        
        private void OnGetCartItemsOperationCompleted(object arg) {
            if ((this.GetCartItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCartItemsCompleted(this, new GetCartItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCartTotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetCartTotal(int userId) {
            object[] results = this.Invoke("GetCartTotal", new object[] {
                        userId});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetCartTotalAsync(int userId) {
            this.GetCartTotalAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetCartTotalAsync(int userId, object userState) {
            if ((this.GetCartTotalOperationCompleted == null)) {
                this.GetCartTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCartTotalOperationCompleted);
            }
            this.InvokeAsync("GetCartTotal", new object[] {
                        userId}, this.GetCartTotalOperationCompleted, userState);
        }
        
        private void OnGetCartTotalOperationCompleted(object arg) {
            if ((this.GetCartTotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCartTotalCompleted(this, new GetCartTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveFromCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveFromCart(int cartId) {
            object[] results = this.Invoke("RemoveFromCart", new object[] {
                        cartId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(int cartId) {
            this.RemoveFromCartAsync(cartId, null);
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(int cartId, object userState) {
            if ((this.RemoveFromCartOperationCompleted == null)) {
                this.RemoveFromCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveFromCartOperationCompleted);
            }
            this.InvokeAsync("RemoveFromCart", new object[] {
                        cartId}, this.RemoveFromCartOperationCompleted, userState);
        }
        
        private void OnRemoveFromCartOperationCompleted(object arg) {
            if ((this.RemoveFromCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveFromCartCompleted(this, new RemoveFromCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateQuantity(int cartId, int quantity) {
            object[] results = this.Invoke("UpdateQuantity", new object[] {
                        cartId,
                        quantity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateQuantityAsync(int cartId, int quantity) {
            this.UpdateQuantityAsync(cartId, quantity, null);
        }
        
        /// <remarks/>
        public void UpdateQuantityAsync(int cartId, int quantity, object userState) {
            if ((this.UpdateQuantityOperationCompleted == null)) {
                this.UpdateQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateQuantityOperationCompleted);
            }
            this.InvokeAsync("UpdateQuantity", new object[] {
                        cartId,
                        quantity}, this.UpdateQuantityOperationCompleted, userState);
        }
        
        private void OnUpdateQuantityOperationCompleted(object arg) {
            if ((this.UpdateQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateQuantityCompleted(this, new UpdateQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckoutAndSaveOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckoutAndSaveOrders(int userId) {
            object[] results = this.Invoke("CheckoutAndSaveOrders", new object[] {
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckoutAndSaveOrdersAsync(int userId) {
            this.CheckoutAndSaveOrdersAsync(userId, null);
        }
        
        /// <remarks/>
        public void CheckoutAndSaveOrdersAsync(int userId, object userState) {
            if ((this.CheckoutAndSaveOrdersOperationCompleted == null)) {
                this.CheckoutAndSaveOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckoutAndSaveOrdersOperationCompleted);
            }
            this.InvokeAsync("CheckoutAndSaveOrders", new object[] {
                        userId}, this.CheckoutAndSaveOrdersOperationCompleted, userState);
        }
        
        private void OnCheckoutAndSaveOrdersOperationCompleted(object arg) {
            if ((this.CheckoutAndSaveOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckoutAndSaveOrdersCompleted(this, new CheckoutAndSaveOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCartItemsCompletedEventHandler(object sender, GetCartItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCartItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCartItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCartTotalCompletedEventHandler(object sender, GetCartTotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCartTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCartTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveFromCartCompletedEventHandler(object sender, RemoveFromCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveFromCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveFromCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateQuantityCompletedEventHandler(object sender, UpdateQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckoutAndSaveOrdersCompletedEventHandler(object sender, CheckoutAndSaveOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckoutAndSaveOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckoutAndSaveOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591